version: "3.4"
services:
  node:
    image: linBox:5000/hellonode:v2
    build:
      context: ./../hello-Node
    ports:
      - "80:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  php:
    image: linBox:5000/hellophp:v2
    build:
      context: ./../hello-Php
    ports:
      - "81:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  go:
    image: linBox:5000/hellogo:v2
    build:
      context: ./../hello-Go
    ports:
      - "82:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
volumes:
  hello-data:
